{
 "title": "ESXI",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Esxi-1 - Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "temperature_esxi_host" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-1 - CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-1 - RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    }
   ]
  },
  {
   "title": "Esxi -1 Data0 - Free Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data0" }
     ]
    }
   ]
  },
  {
   "title": "Esxi -1 Data1 - Free Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data1" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-2 - CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-2 - RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Esxi -1 Data0_HDD - Free Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data0_HDD" }
     ]
    }
   ]
  },
  {
   "title": "Esxi -1 Data1_SSD - Free Space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data1_SSD" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-1 - VM CPU Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "srv-ubn-services-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-1" }
     ]
    },
    {
     "alias": "srv-ubuntu16-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubuntu16-1" }
     ]
    },
    {
     "alias": "srv-win-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-win-1" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-1 - VM RAM Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "srv-ubn-services-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-1" }
     ]
    },
    {
     "alias": "srv-ubuntu16-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubuntu16-1" }
     ]
    },
    {
     "alias": "srv-win-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-win-1" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-2 - VM CPU Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Esxi-2 - VM RAM Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU - Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "hertz", "label": "Clock" }
   ],
   "targets": [
    {
     "alias": "esxi-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "cpu_usage_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    },
    {
     "alias": "esxi-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "cpu_usage_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Host RAM - Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "alias": "esxi-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    },
    {
     "alias": "esxi-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Host Network- Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Kbits", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "esxi-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    },
    {
     "alias": "esxi-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    },
    {
     "alias": "esxi-2 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    },
    {
     "alias": "esxi-2 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Host - Free Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes", "label": "Space" }
   ],
   "targets": [
    {
     "alias": "Esxi-1 - Data0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data0" }
     ]
    },
    {
     "alias": "Esxi-1 - Data1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data1" }
     ]
    },
    {
     "alias": "Esxi-2 - Data0_HDD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data0_HDD" }
     ]
    },
    {
     "alias": "Esxi-2 - Data1_SSD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "ds_name", "operator": "=", "value": "Data1_SSD" }
     ]
    }
   ]
  },
  {
   "title": "VM CPU - Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz", "label": "Clock" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usagemhz_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM RAM - Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "kbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "mem_consumed_maximum" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM Network- Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Kbits", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "srv-ubn-services-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-1" }
     ]
    },
    {
     "alias": "srv-ubn-services-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-1" }
     ]
    },
    {
     "alias": "srv-ubuntu16-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubuntu16-1" }
     ]
    },
    {
     "alias": "srv-ubuntu16-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubuntu16-1" }
     ]
    },
    {
     "alias": "srv-win-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-win-1" }
     ]
    },
    {
     "alias": "srv-win-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-win-1" }
     ]
    },
    {
     "alias": "fw-pfsense-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fw-pfsense-1" }
     ]
    },
    {
     "alias": "fw-pfsense-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "fw-pfsense-1" }
     ]
    },
    {
     "alias": "srv-ubn-media-1 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-media-1" }
     ]
    },
    {
     "alias": "srv-ubn-media-1 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-media-1" }
     ]
    },
    {
     "alias": "srv-ubn-services-2 - RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-2" }
     ]
    },
    {
     "alias": "srv-ubn-services-2 - TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "srv-ubn-services-2" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - VM",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "vsphere_virtualmachine",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime - Host",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "alias": "esx-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-1" }
     ]
    },
    {
     "alias": "esx-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "vsphere_hostsystem",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "esx-2" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Esxi-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "temperature_esxi_host" }
     ]
    }
   ]
  }
 ]
}