{
 "title": "Network",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WAN Interface - Volumen",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "host_192.168.1.158_interface_em2_traffic_total_bytes",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - Traffic in",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "AP-UNFI-1 - Traffic in",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "unifiIfName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiIfTable",
     "select": [
      [
       { "params": [ "unifiIfRxPackets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiIfName", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - Traffic out",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "AP-UNFI-1 - Traffic out",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "unifiIfName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiIfTable",
     "select": [
      [
       { "params": [ "unifiIfTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiIfName", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "WAN Interface - Verteilung per Applikation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "target": "host_192.168.1.158_interface_em2_allprotocols_bps",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "WAN Interface - Verkehr per Applikation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "Durchsatz" }
   ],
   "targets": [
    {
     "target": "host_192.168.1.158_interface_em2_allprotocols_bps",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Internet - Geschwindigkeit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Mbits", "label": "Durchsatz" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Mbit/s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "speedtest_download" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Mbit/s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "speedtest_upload" }
     ]
    }
   ]
  },
  {
   "title": "WAN Interface - Verkehr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "Durchsatz" }
   ],
   "targets": [
    {
     "target": "host_192.168.1.158_interface_em2_traffic_bps",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - 5G Verkehr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "Durchsatz" }
   ],
   "targets": [
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath0" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath1" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath2" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath3" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath4" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - 2.4G Verkehr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "Durchsatz" }
   ],
   "targets": [
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath0" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath1" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath2" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath3" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapRxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "unifiVapTxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath4" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  },
  {
   "title": "Internet - Latenz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms", "label": "RTT" }
   ],
   "targets": [
    {
     "alias": "20min.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "20min.ch" }
     ]
    },
    {
     "alias": "amazon.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "amazon.com" }
     ]
    },
    {
     "alias": "google.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "instagram.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "instagram.com" }
     ]
    },
    {
     "alias": "netflix.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "netflix.com" }
     ]
    },
    {
     "alias": "reddit.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "reddit.com" }
     ]
    },
    {
     "alias": "swisscom.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "swisscom.ch" }
     ]
    },
    {
     "alias": "twitter.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "twitter.com" }
     ]
    },
    {
     "alias": "youtube.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "youtube.com" }
     ]
    },
    {
     "alias": "wikipedia.org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "wikipedia.org" }
     ]
    },
    {
     "alias": "github.com",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "github.com" }
     ]
    },
    {
     "alias": "blick.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "blick.ch" }
     ]
    },
    {
     "alias": "bluewin.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "bluewin.ch" }
     ]
    },
    {
     "alias": "admin.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "admin.ch" }
     ]
    },
    {
     "alias": "sbb.ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "sbb.ch" }
     ]
    },
    {
     "alias": "Wingo Lausanne",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "speedtest-ls.wingo.ch" }
     ]
    },
    {
     "alias": "Wingo Zürich",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "srv-ubn-services-1" },
      { "condition": "AND", "key": "url", "operator": "=", "value": "speedtest.wingo.ch" }
     ]
    }
   ]
  },
  {
   "title": "UNFI-AP-1 - Fehler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifDescr:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifTable",
     "query": "SELECT non_negative_derivative(last(\"ifInDiscards\"), 1s) AS \"Drop:In\", non_negative_derivative(last(\"ifOutDiscards\"), 1s) AS \"Drop:Out\", non_negative_derivative(last(\"ifInErrors\"), 1s) AS \"Error:In\", non_negative_derivative(last(\"ifOutErrors\"), 1s) AS \"Error:Out\", non_negative_derivative(last(\"ifInUnknownProtos\"), 1s) AS \"Unkwn:In\" FROM \"ifTable\" WHERE \"agent_host\" =~ /^$host$/ AND \"ifOperStatus\" = 1 AND $timeFilter GROUP BY time($interval), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Unkwn:In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" }
     ]
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - 5G Qualität",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath0" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath1" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath2" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath3" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath4" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
     ]
    }
   ]
  },
  {
   "title": "AP-UNFI-1 - 2.4G Qualität",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath0" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath1" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath2" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath3" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    },
    {
     "alias": "$tag_unifiVapName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "unifiVapName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unifiVapTable",
     "select": [
      [
       { "params": [ "unifiVapCcq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "AP-UNIFI-1" },
      { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath4" },
      { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
     ]
    }
   ]
  }
 ]
}